@file:OptIn(androidx.compose.foundation.layout.ExperimentalLayoutApi::class)
package cn.aitavern.app

import androidx.compose.foundation.*
import androidx.compose.foundation.gestures.rememberTransformableState
import androidx.compose.foundation.gestures.transformable
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.graphics.TransformOrigin
import androidx.compose.ui.unit.dp
import cn.aitavern.core.*
import kotlinx.serialization.decodeFromString

@Composable fun ContentControls(vm: TavernViewModel) {
    val pending by vm.contentPending.collectAsState()
    val paused by vm.contentPaused.collectAsState()
    if(pending>0 || paused) Surface(tonalElevation=3.dp) {
        Row(Modifier.fillMaxWidth().padding(horizontal=12.dp),horizontalArrangement=Arrangement.SpaceBetween) {
            UiText(if(pending>0) "翻译 / 导览处理中" else "自动翻译已暂停",Modifier.weight(1f).padding(vertical=12.dp))
            if(pending>0) TextButton(onClick=vm::stopContent) { UiText("停止翻译") }
            else TextButton(onClick={ vm.resumeContent() }) { UiText("恢复自动翻译") }
        }
    }
}

@Composable fun WorldWelcome(vm: TavernViewModel, s: Snapshot, world: World) {
    val contentBusy by vm.contentPending.collectAsState()
    val contentPaused by vm.contentPaused.collectAsState()
    var profile by remember(world.id) { mutableStateOf(s.profiles.firstOrNull()?.id.orEmpty()) }
    var persona by remember(world.id) { mutableStateOf(world.personas.firstOrNull()?.id.orEmpty()) }
    var personaText by remember(world,persona,s.settings.language) { mutableStateOf<String?>(null) }
    var guide by remember(world,s.characters,s.books,s.settings.language,persona) { mutableStateOf("") }
    var generated by remember(world,s.characters,s.books,s.settings.language,persona) { mutableStateOf(emptyList<StoryEntry>()) }
    var localized by remember(world,s.characters,s.settings.language) { mutableStateOf(mapOf<StoryEntry,StoryEntry>()) }
    var selected by remember { mutableStateOf<StoryEntry?>(null) }
    var graph by remember { mutableStateOf(false) }
    var notice by remember { mutableStateOf(false) }
    var pending by remember { mutableStateOf<(() -> Unit)?>(null) }
    fun apiAction(action: () -> Unit) { if(!s.settings.contentApiNoticeSeen) { pending=action; notice=true } else action() }
    LaunchedEffect(world,s.characters,s.books,s.settings.language,persona,profile,s.settings.contentApiNoticeSeen,contentPaused) {
        if(profile.isNotBlank() && s.settings.contentApiNoticeSeen) {
            vm.worldContent(world.id,persona,profile,false,automatic=true) { guide=it }
            vm.worldContent(world.id,persona,profile,true,automatic=true,cachedOnly=true) { generated=TavernJson.decodeFromString(it) }
            world.personas.find { it.id==persona }?.description?.takeIf { it.isNotBlank() }?.let { source -> vm.translate(source,profile,automatic=true) { personaText=it } }
            StoryContent.entries(world,s.characters).forEach { entry -> vm.localizedEntry(entry,profile,automatic=true) { localized=localized+(entry to it) } }
        }
    }
    Column(verticalArrangement=Arrangement.spacedBy(12.dp)) {
        UiText(world.name,style=MaterialTheme.typography.headlineSmall)
        if(contentBusy>0) LinearProgressIndicator(Modifier.fillMaxWidth())
        UiText("世界介绍",style=MaterialTheme.typography.titleMedium)
        var expanded by remember(world.id) { mutableStateOf(false) }
        UiText(guide.ifBlank { world.description.ifBlank { "资料未提供" } },maxLines=if(expanded) Int.MAX_VALUE else 12)
        TextButton(onClick={ expanded=!expanded }) { UiText(if(expanded) "收起" else "展开") }
        UiText("API")
        ChoiceChips(s.profiles.map { it.id to it.name },listOf(profile)) { profile=it.lastOrNull().orEmpty() }
        UiText("可扮演身份")
        ChoiceChips(world.personas.map { it.id to it.name },listOf(persona)) { persona=it.lastOrNull().orEmpty() }
        world.personas.find { it.id==persona }?.let { UiText(personaText ?: it.description) }
        TextButton(onClick={ apiAction { vm.worldContent(world.id,persona,profile,false) { guide=it } } },enabled=profile.isNotBlank()) { UiText("生成 / 翻译世界导览") }
        UiText("认识角色",style=MaterialTheme.typography.titleMedium)
        s.characters.filter { it.id in world.characterIds }.forEach { c ->
            var translated by remember(c,s.settings.language) { mutableStateOf<String?>(null) }
            LaunchedEffect(c.description,c.personality,s.settings.language,profile,s.settings.contentApiNoticeSeen,contentPaused) {
                if(profile.isNotBlank() && s.settings.contentApiNoticeSeen && (c.description.isNotBlank() || c.personality.isNotBlank())) vm.translate(c.description+"\n"+c.personality,profile,automatic=true) { translated=it }
            }
            var expandedCharacter by remember(c.id) { mutableStateOf(false) }
            OutlinedCard(Modifier.fillMaxWidth()) { Column(Modifier.padding(12.dp)) {
                Row { Avatar(c); UiText(c.name,Modifier.padding(8.dp)) }
                UiText(translated ?: (c.description.ifBlank { "资料未提供" }+"\n"+c.personality.ifBlank { "资料未提供" }),maxLines=if(expandedCharacter) Int.MAX_VALUE else 5)
                TextButton(onClick={ expandedCharacter=!expandedCharacter }) { UiText(if(expandedCharacter) "收起" else "展开") }
                TextButton(onClick={ apiAction { vm.translate(c.description+"\n"+c.personality,profile) { translated=it } } },enabled=profile.isNotBlank()) { UiText("翻译") }
            } }
        }
        UiText("故事入口",style=MaterialTheme.typography.titleMedium)
        UiText("选择一个入口即可开始，也可以自定义小剧场。")
        (StoryContent.entries(world,s.characters).map { localized[it] ?: it }+generated).forEach { entry ->
            Card(onClick={ selected=entry },modifier=Modifier.fillMaxWidth()) { Column(Modifier.padding(14.dp)) {
                UiText(entry.title,style=MaterialTheme.typography.titleMedium)
                UiText(entry.background)
                UiText(entry.objective.ifBlank { "自由探索 · 无固定任务" })
                UiText(entry.opening,maxLines=3)
            } }
        }
        Button(onClick={ apiAction { vm.worldContent(world.id,persona,profile,true,refresh=generated.isNotEmpty()) { generated=TavernJson.decodeFromString(it) } } },enabled=profile.isNotBlank() && contentBusy==0) { UiText("生成更多入口（六个）") }
        OutlinedButton(onClick={ graph=true }) { UiText("剧情分支图") }
        HorizontalDivider()
        UiText("已有故事",style=MaterialTheme.typography.titleMedium)
    }
    if(notice) AlertDialog(onDismissRequest={ notice=false; pending=null },title={ UiText("AI 内容服务") },text={ UiText("相关世界和角色资料会发送到所选 API，并消耗额度。生成结果保存在本机。") },confirmButton={ TextButton(onClick={ vm.contentNotice(); notice=false; pending?.invoke(); pending=null }) { UiText("继续") } },dismissButton={ TextButton(onClick={ notice=false; pending=null }) { UiText("取消") } })
    selected?.let { entry ->
        var members by remember(entry) { mutableStateOf(entry.memberIds) }
        var chosenPersona by remember(entry) { mutableStateOf(persona.ifBlank { entry.personaId }) }
        var draft by remember(entry,s.settings.language) { mutableStateOf(entry) }
        Editor("开启故事",{ selected=null },{ vm.startStory(world,draft,profile,members,chosenPersona); selected=null },profile.isNotBlank() && members.size in 1..8,saveLabel="开始") {
            UiText(draft.title); UiText(draft.background); UiText(draft.objective.ifBlank { "自由探索 · 无固定任务" }); UiText(draft.opening)
            TextButton(onClick={ apiAction { vm.translate(draft.opening,profile) { value -> draft=draft.copy(opening=value) } } },enabled=profile.isNotBlank()) { UiText("翻译开场") }
            ChoiceChips(s.profiles.map { it.id to it.name },listOf(profile)) { profile=it.lastOrNull().orEmpty() }
            ChoiceChips(s.characters.filter { it.id in world.characterIds }.map { it.id to it.name },members) { members=it }
            ChoiceChips(world.personas.map { it.id to it.name },listOf(chosenPersona)) { chosenPersona=it.lastOrNull().orEmpty() }
        }
    }
    if(graph) StoryGraph(vm,s,world,{ graph=false })
}

@Composable fun VersionPicker(vm: TavernViewModel, s: Snapshot, room: ChatRoom, close: ()->Unit) {
    Editor("回复版本",close,close,saveLabel="完成",showCancel=false) {
        s.versions.filter { it.roomId==room.id }.sortedBy { it.createdAt }.forEachIndexed { index,v ->
            Card(Modifier.fillMaxWidth()) { Column(Modifier.padding(12.dp)) {
                UiText("${index+1} · ${ui(v.status)}"+if(v.id==room.activeVersionId) " ✓" else "")
                UiText((if(v.id==room.activeVersionId) s.messages.filter { it.roomId==room.id } else v.messages).lastOrNull()?.text.orEmpty(),maxLines=6)
                TextButton(onClick={ vm.switchVersion(v.id); close() },enabled=v.status=="complete" && v.id!=room.activeVersionId) { UiText("切换到此版本") }
            } }
        }
    }
}

@Composable fun StoryGraph(vm: TavernViewModel,s: Snapshot,world: World,close: ()->Unit) {
    val activeRoom by vm.activeRoom.collectAsState()
    var marking by remember { mutableStateOf<ChatRoom?>(null) }
    var zoom by remember { mutableFloatStateOf(1f) }
    var offset by remember { mutableStateOf(Offset.Zero) }
    val transform=rememberTransformableState { z,p,_ -> zoom=(zoom*z).coerceIn(0.4f,2.5f); offset+=p }
    val rooms=s.rooms.filter { it.worldId==world.id }
    fun depth(r: ChatRoom): Int { var n=0; var p=r.parentId; val seen=mutableSetOf(r.id); while(p!=null && seen.add(p)) { n++; p=rooms.find { it.id==p }?.parentId }; return n }
    Editor("剧情分支图",close,close,saveLabel="完成",showCancel=false) {
        UiText("双指缩放 / 拖动，点击路线继续故事。回复版本不增加分支。")
        Row { TextButton(onClick={ zoom=(zoom*1.2f).coerceAtMost(2.5f) }) { UiText("＋") }; TextButton(onClick={ zoom=(zoom/1.2f).coerceAtLeast(0.4f) }) { UiText("－") }; TextButton(onClick={ zoom=1f; offset=Offset.Zero }) { UiText("重置") } }
        val endings=s.endings.filter { e -> rooms.any { it.id==e.roomId && it.activeVersionId==e.versionId } && e.groupId.isNotBlank() && e.fingerprint==StoryContent.fingerprint(s.messages.filter { it.roomId==e.roomId && it.status=="complete" }.sortedBy { it.sequence }.joinToString("\n") { it.text }) }
        val ordered=rooms.sortedWith(compareBy<ChatRoom> { depth(it) }.thenBy { it.createdAt })
        val groups=endings.groupBy { it.groupId }
        val endX=((rooms.maxOfOrNull { depth(it) } ?: 0)+1)*250f
        val positions=ordered.mapIndexed { i,r -> r.id to Offset(depth(r)*250f,i*125f) }.toMap()
        val endPositions=groups.keys.mapIndexed { i,id -> id to Offset(endX,i*125f) }.toMap()
        val lineColor=MaterialTheme.colorScheme.primary
        Box(Modifier.fillMaxWidth().height(420.dp).transformable(transform).horizontalScroll(rememberScrollState()).verticalScroll(rememberScrollState())) {
            Box(Modifier.width((endX+240).dp).height((maxOf(ordered.size,groups.size)*125+30).dp)
                .graphicsLayer(scaleX=zoom,scaleY=zoom,translationX=offset.x,translationY=offset.y,transformOrigin=TransformOrigin(0f,0f))) {
                Canvas(Modifier.matchParentSize()) {
                    fun edge(from: Offset,to: Offset) { drawLine(lineColor,Offset((from.x+205).dp.toPx(),(from.y+38).dp.toPx()),Offset(to.x.dp.toPx(),(to.y+38).dp.toPx()),strokeWidth=2.dp.toPx()) }
                    ordered.forEach { r -> r.parentId?.let { parent -> positions[parent]?.let { edge(it,positions.getValue(r.id)) } } }
                    endings.forEach { e -> edge(positions.getValue(e.roomId),endPositions.getValue(e.groupId)) }
                }
                ordered.forEach { r ->
                    val pos=positions.getValue(r.id)
                    Card(onClick={ vm.activeRoom.value=r.id; close() },modifier=Modifier.offset(pos.x.dp,pos.y.dp).width(205.dp).height(105.dp)) {
                        Column(Modifier.padding(10.dp)) {
                            UiText((if(r.parentId==null) "● " else "↳ ")+r.name+(if(activeRoom==r.id) " ✓" else ""),maxLines=2)
                            if(r.parentId!=null) UiText(r.branchChoice.ifBlank { ui("分歧位置未知") },maxLines=2)
                        }
                    }
                }
                groups.forEach { (id,group) ->
                    val pos=endPositions.getValue(id)
                    OutlinedCard(Modifier.offset(pos.x.dp,pos.y.dp).width(210.dp).height(105.dp)) {
                        Column(Modifier.padding(10.dp)) { UiText("◎ "+group.first().title,maxLines=2); UiText(group.first().outcome,maxLines=2) }
                    }
                }
            }
        }
        rooms.forEach { r -> TextButton(onClick={ marking=r }) { UiText(r.name+" · "+ui("标记结局")) } }
        endings.groupBy { it.groupId }.forEach { (_,group) ->
            UiText(group.joinToString(" + ") { e -> rooms.find { it.id==e.roomId }?.name.orEmpty() }+" → ◎ "+group.first().title)
            group.forEach { ending ->
                UiText(ending.reason)
                TextButton(onClick={ vm.setEndingGroup(ending,null) }) { UiText("撤销收束") }
                endings.filter { it.groupId!=ending.groupId && storyRoot(rooms,it.roomId)==storyRoot(rooms,ending.roomId) }.distinctBy { it.groupId }.forEach { target ->
                    TextButton(onClick={ vm.setEndingGroup(ending,target.groupId) }) { UiText("→ ${target.title}") }
                }
            }
        }
    }
    marking?.let { room ->
        var title by remember(room.id) { mutableStateOf("") }; var outcome by remember(room.id) { mutableStateOf("") }
        Editor("标记结局",{ marking=null },{ vm.markEnding(room.id,title,outcome); marking=null },title.isNotBlank() && outcome.isNotBlank()) {
            Field("名字",title,{ title=it }); Field("结局结果",outcome,{ outcome=it },3)
        }
    }

}

private fun storyRoot(rooms: List<ChatRoom>, id: String): String {
    var current=id; val visited=mutableSetOf<String>()
    while(visited.add(current)) current=rooms.find { it.id==current }?.parentId ?: return current
    return id
}
